# CẤU HÌNH DATABASE CHO MÔI TRƯỜNG CHẠY THỰC TẾ (PROD - PostgreSQL Supabase)
spring.datasource.url=${DB_URL:***REMOVED***-DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:***REMOVED***-DB_USERNAME}
spring.datasource.password=${DB_PASSWORD:***REMOVED***-DB_PASSWORD}

# CẤU HÌNH HIBERNATE DIALECT CHO POSTGRESQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
